### ISSUE TITLE
Ladrillos

### ISSUE THREAD

**Issue by zeratulmdq** [UTN-MDP/ArkanoidJS#2]
Hay que implementar el dibujo de los ladrillos y el destruirlos cuando se golpean (una sola vez). Por el momento, solo un nivel.

**Comment by zeratulmdq** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Arkanoid - Ladrillos](https://trello.com/c/wn2k5KYt/1-arkanoid-ladrillos)

**Comment by fedealdosivi** [comment]
hago este

**Comment by zeratulmdq** [comment]
Cerrado por #7
