### ISSUE TITLE
Reinicio del juego

### ISSUE THREAD

**Issue by zeratulmdq** [UTN-MDP/ArkanoidJS#5]
Cuando termina el juego la única manera de volver a empezar es reiniciando la página. Crear un botón de inicio/reinicio que permita volver a empezar sin que esto suceda.

**Comment by zeratulmdq** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Arkanoid - Reinicio](https://trello.com/c/yyVyrqpB/3-arkanoid-reinicio)

**Comment by SantiBlanc87** [comment]
Yo me encargo de este issue, Tincho.

**Comment by SantiBlanc87** [comment]
Creo que está listo. Se le hace una especie de log con los cambios? O solo comentando el código?

**Comment by zeratulmdq** [comment]
Se hace un PR y se trabaja sobre eso. Los cambios quedan en la historia de git y en el commit correspondiente, que deberia detallar lo que hiciste (no un libro, pero si un changelist y acotaciones que crean pertinentes).

**Comment by SantiBlanc87** [comment]
Entendido. Hoy a la noche en la facu entonces lo hago (y).
